# -*- coding: utf-8 -*-
"""
/***************************************************************************
 MultiOffset
                                 A QGIS plugin
 Offset multiple lines at once
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2025-10-11
        copyright            : (C) 2025 by ChuckWagon Computing
        email                : david@chuckwagoncomputing.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""

__author__ = 'ChuckWagon Computing'
__date__ = '2025-10-11'
__copyright__ = '(C) 2025 by ChuckWagon Computing'


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load MultiOffset class from file MultiOffset.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .multi_offset import MultiOffsetPlugin
    return MultiOffsetPlugin()
