# -*- coding: utf-8 -*-

"""
/***************************************************************************
 MultiOffset
                                 A QGIS plugin
 Offset multiple lines at once
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2025-10-11
        copyright            : (C) 2025 by ChuckWagon Computing
        email                : david@chuckwagoncomputing.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

__author__ = 'ChuckWagon Computing'
__date__ = '2025-10-11'
__copyright__ = '(C) 2025 by ChuckWagon Computing'

# This will get replaced with a git SHA1 when you do a git archive

__revision__ = '$Format:%H$'

from qgis.PyQt.QtCore import QCoreApplication
from qgis.core import (QgsProcessing,
                       QgsVectorLayer,
                       QgsProcessingAlgorithm,
                       QgsProcessingParameterMultipleLayers,
                       QgsProcessingParameterFeatureSink,
                       QgsProcessingMultiStepFeedback,
                       QgsProcessingLayerPostProcessorInterface)
import processing

class MultiOffsetAlgorithm(QgsProcessingAlgorithm):
    """
    This is an example algorithm that takes a vector layer and
    creates a new identical one.

    It is meant to be used as an example of how to create your own
    algorithms and explain methods and variables used to do it. An
    algorithm like this will be available in all elements, and there
    is not need for additional work.

    All Processing algorithms should extend the QgsProcessingAlgorithm
    class.
    """

    # Constants used to refer to parameters and outputs. They will be
    # used when calling the algorithm from another algorithm, or when
    # calling from the QGIS console.

    LAYERS = 'LAYERS'
    OUTPUT = 'OUTPUT'

    def initAlgorithm(self, config):
        """
        Here we define the inputs and output of the algorithm, along
        with some other properties.
        """

        self.__step = 0

        self.addParameter(
            QgsProcessingParameterMultipleLayers(
                self.LAYERS,
                self.tr('Input layers'),
                QgsProcessing.TypeVector
            )
        )


        # We add a feature sink in which to store our processed features (this
        # usually takes the form of a newly created vector layer when the
        # algorithm is run in QGIS).
        self.addParameter(
            QgsProcessingParameterFeatureSink(
                self.OUTPUT,
                self.tr('Output layer')
            )
        )

    def __nextStep(self, feedback):
        self.__step += 1
        feedback.setCurrentStep(self.__step)
        if feedback.isCanceled():
            return False
        return True

    def processAlgorithm(self, parameters, context, feedback):
        """
        Here is where the processing itself takes place.
        """

        # Retrieve the feature source and sink. The 'dest_id' variable is used
        # to uniquely identify the feature sink, and must be included in the
        # dictionary returned by the processAlgorithm function.
        sources = self.parameterAsLayerList(parameters, self.LAYERS, context)

        n_steps = len(sources) * 2 + 3
        child_feedback = QgsProcessingMultiStepFeedback(n_steps, feedback)

        sources_valid = []
        for s in sources:
            field_index = s.fields().indexOf('layer')
            if field_index != -1:
                s.dataProvider().deleteAttributes([field_index])
                s.updateFields()

            i_explodelines = {
                'INPUT': s,
                'OUTPUT': QgsProcessing.TEMPORARY_OUTPUT
            }
            s_exploded = processing.run("native:explodelines", i_explodelines,
                context=context, feedback=child_feedback, is_child_algorithm=True)
            if not self.__nextStep(child_feedback): return {}

            i_checkvalidity = {
                'INPUT_LAYER': s_exploded['OUTPUT'],
                'METHOD': 2,
                'IGNORE_RING_SELF_INTERSECTION': False,
                'VALID_OUTPUT': 'memory:' + s.name()
            }
            s_valid = processing.run("native:checkvalidity", i_checkvalidity,
                context=context, feedback=child_feedback, is_child_algorithm=True)
            sources_valid.append(s_valid['VALID_OUTPUT'])
            if not self.__nextStep(child_feedback): return {}

        i_mergevectorlayers = {
            'LAYERS': sources_valid,
            'CRS': None,
            'OUTPUT': QgsProcessing.TEMPORARY_OUTPUT,
            'ADD_SOURCE_FIELDS': True
        }
        s_merged = processing.run("native:mergevectorlayers", i_mergevectorlayers,
            context=context, feedback=child_feedback, is_child_algorithm=True)
        if not self.__nextStep(child_feedback): return {}

        i_offsetter = {
            'INPUT': s_merged['OUTPUT'],
            'OUTPUT': QgsProcessing.TEMPORARY_OUTPUT,
            'CATEGORY_FIELD': 'layer'
        }
        s_offset = processing.run("Offsetter:Offsetter", i_offsetter,
            context=context, feedback=child_feedback, is_child_algorithm=True)
        if not self.__nextStep(child_feedback): return {}

        i_dissolve = {
            'INPUT': s_offset['OUTPUT'],
            'FIELD': ['layer','offset'],
            'SEPARATE_DISJOINT': False,
            'OUTPUT': parameters[self.OUTPUT]
        }
        s_dissolve = processing.run("native:dissolve", i_dissolve,
            context=context, feedback=child_feedback, is_child_algorithm=True)

        if context.willLoadLayerOnCompletion(s_dissolve['OUTPUT']):
            context.layerToLoadOnCompletionDetails(s_dissolve['OUTPUT'])\
                .setPostProcessor(MultiOffsetPostProcessor.create())

        # Return the results of the algorithm. In this case our only result is
        # the feature sink which contains the processed features, but some
        # algorithms may return multiple feature sinks, calculated numeric
        # statistics, etc. These should all be included in the returned
        # dictionary, with keys matching the feature corresponding parameter
        # or output names.
        return { self.OUTPUT: s_dissolve['OUTPUT'] }

    def name(self):
        """
        Returns the algorithm name, used for identifying the algorithm. This
        string should be fixed for the algorithm, and must not be localised.
        The name should be unique within each provider. Names should contain
        lowercase alphanumeric characters only and no spaces or other
        formatting characters.
        """
        return 'Offset Multiple'

    def displayName(self):
        """
        Returns the translated algorithm name, which should be used for any
        user-visible display of the algorithm name.
        """
        return self.tr(self.name())

    def group(self):
        """
        Returns the name of the group this algorithm belongs to. This string
        should be localised.
        """
        return self.tr(self.groupId())

    def groupId(self):
        """
        Returns the unique ID of the group this algorithm belongs to. This
        string should be fixed for the algorithm, and must not be localised.
        The group id should be unique within each provider. Group id should
        contain lowercase alphanumeric characters only and no spaces or other
        formatting characters.
        """
        return ''

    def tr(self, string):
        return QCoreApplication.translate('Processing', string)

    def createInstance(self):
        return MultiOffsetAlgorithm()

# Courtesy of Nyall Dawson: https://gist.github.com/nyalldawson/26c091dd48b4f8bf56f172efe22cf75f
class MultiOffsetPostProcessor(QgsProcessingLayerPostProcessorInterface):

    instance = None

    def postProcessLayer(self, layer, context, feedback):  # pylint: disable=unused-argument
        if not isinstance(layer, QgsVectorLayer):
            return

        # Do any non-thread safe post-processing here.
        # Set a style for your layer etc.
        layer.setName('Offset')

    # Hack to work around sip bug!
    @staticmethod
    def create() -> 'MultiOffsetPostProcessor':
        """
        Returns a new instance of the post processor, keeping a reference to the sip
        wrapper so that sip doesn't get confused with the Python subclass and call
        the base wrapper implementation instead... ahhh sip, you wonderful piece of sip
        """
        MultiOffsetPostProcessor.instance = MultiOffsetPostProcessor()
        return MultiOffsetPostProcessor.instance
